---
- hosts: dietpi
  become: true
  gather_facts: true

  tasks:
  - name: Refresh repository on apt
    apt:
      update_cache: true
    register: updateapt
    when: ansible_pkg_mgr=="apt"
  - debug: var=updateapt

  - name: Install docker on apt
    apt:
      name: docker.io
      state: latest
    register: installapt
    when: ansible_pkg_mgr=="apt"
  - debug: var=installapt

  - name: Refresh repository on yum
    yum:
      update_cache: true
    register: updateyum
    when: ansible_pkg_mgr=="yum"
  - debug: var=updateyum

  - name: Install docker on yum
    yum:
      name: docker.io
      state: latest
    register: installyum
    when: ansible_pkg_mgr=="yum"
  - debug: var=installyumi
